//USER ACTIONS
export const SIGNING_UP_USER = 'SIGNING_UP_USER';
export const LOGGING_IN_USER = 'LOGGING_IN_USER';
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATED_USER = 'UPDATED_USER';
export const GET_AGENT_DETAILS = 'GET_AGENT_DETAILS'
export const FETCHING_AGENTS_DETAILS = 'FETCHING_AGENTS_DETAILS';
export const SAVE_FETCHED_AGENTS = 'SAVE_FETCHED_AGENTS';


//LOCATION ACTIONS
export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';