//USER ACTIONS
export const SIGNING_UP_USER = 'SIGNING_UP_USER';
export const LOGGING_IN_USER = 'LOGGING_IN_USER';
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCHING_EMPLOYEE_DETAILS = 'FETCHING_EMPLOYEE_DETAILS';
export const FETCHED_EMPLOYEE_DETAILS = 'FETCHED_EMPLOYEE_DETAILS';

//LOCATION ACTIONS
export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';

// PROJECT ACTIONS
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const FETCHED_PROJECTS = 'FETCHED_PROJECTS';
export const CREATING_PROJECT = 'CREATING_PROJECT';
export const CREATED_PROJECT = 'CREATED_PROJECT';
export const UPDATING_PROJECT = 'UPDATING_PROJECT';
export const UPDATED_PROJECT = 'CUPDATD_PROJECT';
export const DELETING_PROJECT = 'DELETING_PROJECT';
export const DELETED_PROJECT = 'DELETED_PROJECT';
export const ASSIGNING_DEASSIGNING_USER_FROM_PROJECT = 'ASSIGNING_DEASSIGNING_USER_FROM_PROJECT';
export const ASSIGNED_DEASSIGNED_USER_FROM_PROJECT = 'ASSIGNED_DEASSIGNED_USER_FROM_PROJECT';
export const FETCHING_PROJECT_LOGS = 'FETCHING_PROJECTS_LOGS';
export const FETCHED_PROJECT_LOGS = 'FETCHED_PROJECTS_LOGS';

// SNACKBAR ACTIONS
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR'

//chat actions
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE';
export const FETCHING_CHAT_MESSAGES = 'FETCHING_CHAT_MESSAGES';
export const FETCHED_CHAT_MESSAGES = 'FETCHED_CHAT_MESSAGES';
export const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';

//Client/Admin user actions
export const FETCHED_USERS = 'FETCHED_USERS';
export const FETCHING_USERS = 'FETCHING_USERS';
export const SAVING_USERS = 'SAVING_USERS';
export const SAVED_USERS = 'SAVED_USERS';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATED_USER = 'UPDATED_USER';
export const FETCHING_AUTH_USER = 'FETCHING_AUTH_USER';
export const FETCHED_AUTH_USER = 'FETCHED_AUTH_USER';

// CLIENTS ACTIONS
export const FETCHING_CLIENTS = 'FETCHING_CLIENTS';
export const FETCHED_CLIENTS = 'FETCHED_CLIENTS';
export const SAVING_CLIENT = 'SAVING_CLIENT';
export const SAVED_CLIENT = 'SAVED_CLIENT';
export const UPDATING_CLIENT = 'UPDATING_CLIENT';
export const UPDATED_CLIENT = 'UPDATED_CLIENT';

// PROJECT ITEMS ACTIONS

export const FETCHING_PROJECT_ITEMS = 'FETCHING_PROJECT_ITEMS';
export const FETCHED_PROJECT_ITEMS = 'FETCHED_PROJECT_ITEMS';
export const CREATING_PROJECT_ITEM = 'CREATING_PROJECT_ITEM';
export const CREATED_PROJECT_ITEM = 'CREATED_PROJECT_ITEM';
export const UPDATING_PROJECT_ITEM = 'UPDATING_PROJECT_ITEM';
export const UPDATED_PROJECT_ITEM = 'CUPDATD_PROJECT_ITEM';
export const DELETING_PROJECT_ITEM = 'DELETING_PROJECT_ITEM';
export const DELETED_PROJECT_ITEM = 'DELETED_PROJECT_ITEM';

//ATTACHMENTS
export const FETCHING_ATTACHMENTS = 'FETCHING_ATTACHMENTS';
export const FETCHED_ATTACHMENTS = 'FETCHED_ATTACHMENTS';